application: "sdfge10"
version: 2
runtime: python
api_version: 1

handlers:
- url: /media
  static_dir: media

- url: /prefs
  script: datastore_example.py
  login: required 

- url: /
  script: datastore_example.py
